# Generated by Django 3.2.16 on 2025-04-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20250422_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название сообщества')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг названия сообщества')),
                ('description', models.TextField(verbose_name='Описание сообщества')),
            ],
            options={
                'verbose_name': 'сообщество',
                'verbose_name_plural': 'Сообщества',
            },
        ),
    ]
